#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#Python 2.7.9

x=1
y=2
z=0
s=0
while y<4000000:
    if y%2==0:
        s += y
    z = x+y
    x = y
    y = z
    print x,y
print s
    
    
